const test = require('tape')
const func = require('./teste')
/*
test('aplicar desconto padrão', (t) => {t.assert(func.aplicardesconto(10,5)=== 5, "desconto true 01")
t.end()
})
test('aplicar desconto padrão', (t) => {t.assert(func.aplicardesconto(11,5)=== 5, "desconto false 02")
t.end()
})
test('aplicar desconto padrão', (t) => {t.assert(func.aplicardesconto(20,5)=== 15, "desconto true 03")
t.end()
})
test('aplicar desconto padrão', (t) => {t.assert(func.aplicardesconto(100,50)=== 50, "desconto true 04")
t.end()
})
test('aplicar desconto padrão', (t) => {t.assert(func.aplicardesconto(1000,500)=== 5, "desconto true 05")
t.end()
})
*/
test('validar numero', (t) => {t.assert(func.validarnumero(1000)=== true, "validação")
t.end()
})
test('validar numero', (t) => {t.assert(func.validarnumero('lukas')=== true, "validação")
t.end()
})